package:
  name: libibverbs-cos7-x86_64
  version: 22.4.2

source:
  - url: http://mirror.centos.org/centos/7/updates/x86_64/Packages/libibverbs-22.4-2.el7_8.x86_64.rpm
    sha256: 71fc3dbd64bc67e891b008eb8a98b5acb60b99d766e24f3a6d5963466671a3e0
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/updates/Source/SPackages/rdma-core-22.4-2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - rdma-core-copyright.txt
    - rdma-core-bsd-fb.txt
    - rdma-core-bsd-mit.txt
    - rdma-core-gpl2.txt
  summary: "(CDT) A library for direct userspace use of RDMA (InfiniBand/iWARP) hardware"
  description: |
        libibverbs is a library that allows userspace processes to use RDMA "verbs" as
        described in the InfiniBand Architecture Specification and the RDMA Protocol
        Verbs Specification.  This includes direct hardware access from userspace to
        InfiniBand/iWARP adapters (kernel bypass) for fast path operations.  For this
        library to be useful, a device-specific plug-in module should also be
        installed.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
