package:
  name: numactl-cos7-x86_64
  version: 2.0.12

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/numactl-2.0.12-5.el7.x86_64.rpm
    sha256: 44c09f9002dcd478e3334403c808e9029e6533bf1d558d34c11f54ee397800d5
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/numactl-2.0.12-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: ftp://oss.sgi.com/www/projects/libnuma/download
  license: LGPLv2/GPLv2
  license_family: GPL2
  license_file:
    - numactl-copyright.txt
    - numactl-gpl2.txt
    - numactl-lgpl2.txt
  summary: (CDT) Library for tuning for Non Uniform Memory Access machines
  description: |
    Simple NUMA policy support. It consists of a numactl program to run other
    programs with a specific NUMA policy and a libnuma to do allocations with NUMA
    policy in applications.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
