package:
  name: libibverbs-devel-cos7-x86_64
  version: 22.4.2

source:
  - url: http://mirror.centos.org/centos/7/updates/x86_64/Packages/rdma-core-devel-22.4-2.el7_8.x86_64.rpm
    sha256: 7a6930d4bf8bf67216491192315a8b18230c7db4e5dd029bad326ad541d201fc
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/updates/Source/SPackages/rdma-core-22.4-2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libibverbs-cos7-x86_64 ==22.4.2 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libibverbs-cos7-x86_64 ==22.4.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - libibverbs-cos7-x86_64 ==22.4.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - rdma-core-copyright.txt
    - rdma-core-bsd-fb.txt
    - rdma-core-bsd-mit.txt
    - rdma-core-gpl2.txt
  summary: (CDT) Development files for the libibverbs library
  description: |
    Header files for the libibverbs library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
