package:
  name: ibacm
  version: 22.4.2

source:
  - url: http://mirror.centos.org/centos/7/updates/x86_64/Packages/ibacm-22.4-2.el7_8.x86_64.rpm
    sha256: a0c2b70dd1c7ec56e3c70a78679e18eaaf9b09264cda5996bc97e59fdee3308b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/updates/Source/SPackages/rdma-core-22.4-2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - rdma-core-copyright.txt
    - rdma-core-bsd-fb.txt
    - rdma-core-bsd-mit.txt
    - rdma-core-gpl2.txt
  summary: "(CDT) InfiniBand Communication Manager Assistant"
  description: |
        The ibacm daemon helps reduce the load of managing path record lookups on
        large InfiniBand fabrics by providing a user space implementation of what
        is functionally similar to an ARP cache.  The use of ibacm, when properly
        configured, can reduce the SA packet load of a large IB cluster from O(n^2)
        to O(n).  The ibacm daemon is started and normally runs in the background,
        user applications need not know about this daemon as long as their app
        uses librdmacm to handle connection bring up/tear down.  The librdmacm
        library knows how to talk directly to the ibacm daemon to retrieve data.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
