package:
  name: numactl-devel-cos7-x86_64
  version: 2.0.12

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/numactl-devel-2.0.12-5.el7.x86_64.rpm
    sha256: 11c48961d93dbcbef519b2d50df43198c572e3a8a335d62ebc1e5f6307d948e5
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/numactl-2.0.12-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - numactl-cos7-x86_64 ==2.0.12 *_{{ cdt_build_number|int + 1000 }}
  host:
    - numactl-cos7-x86_64 ==2.0.12 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - numactl-cos7-x86_64 ==2.0.12 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: ftp://oss.sgi.com/www/projects/libnuma/download
  license: LGPLv2/GPLv2
  license_family: GPL2
  license_file:
    - numactl-copyright.txt
    - numactl-gpl2.txt
    - numactl-lgpl2.txt
  summary: (CDT) Development package for building Applications that use numa
  description: |
    Provides development headers for numa library calls

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
